### ISSUE TITLE
OUTPUT Page formatting issue

### ISSUE THREAD

**Issue by arjunachala** [hpccsystems-solutions-lab/Learn-ECL#15]
![image](https://user-images.githubusercontent.com/999180/161555758-24c92494-e5eb-4426-9e0a-4debfa008a28.png)

**Comment by dcamper** [comment]
<img width="1810" alt="Screen Shot 2022-05-09 at 14 21 42" src="https://user-images.githubusercontent.com/1508532/167482340-9fe929e1-c3d5-4dfe-9dc0-456b7983106c.png">

Enclosed screenshot from Safari displaying on my primary laptop screen.  It opens that way, and there is not enough horizontal screen space to uncover the primary pane's information.  As far as I can see, there is no valid reason for requiring such a large minimum horizontal width.

On a wide screen, resizing the window's width (making it more narrow) dynamically moves the primary pane's content under the left nav area, partially hiding it.  This should never happen.

The above description is specifically relating to the Output section of the site (https://learn.hpccsystems.com/hpcc/Tutorial/ECLSyntax/output).  The Denormalize section (https://learn.hpccsystems.com/hpcc/Tutorial/ECLSyntax/denormalize) has the same dynamic resizing problems, but does not have the same initial width problem as Output.

**Comment by BaharF** [comment]
Thank you Dan, 
This issue was addressed a few weeks back and it was resolved. I will try to bring this up again.

**Comment by dcamper** [comment]
@BaharF Ah, I thought the issue was still open and I was just adding more info.  Thanks for following up!

**Comment by BaharF** [comment]
Fixed.
